[manifest]
version = "1.0.0"
priority = 0
dump_lua = true

[[patches]]
[patches.module]
source = "twitch/api.lua"
name = "twitch.api"

[[patches]]
[patches.module]
source = "twitch/auth.lua"
name = "twitch.auth"

[[patches]]
[patches.module]
source = "twitch/chat.lua"
name = "twitch.chat"

[[patches]]
[patches.module]
source = "twitch/lib.lua"
name = "twitch.lib"

[[patches]]
[patches.pattern]
target = "main.lua"
pattern = '''function love.quit()'''
position = "after"
payload = '''
    if SMODS.Mods["twitchintegration"].twitch_auth then
        SMODS.Mods["twitchintegration"].twitch_auth:abort_auth()
    end
'''
match_indent = true
